### ISSUE TITLE
Mistake at mockup "List of Products"

### ISSUE THREAD

**Issue by ArtemTereshkovich** [messi3nik/DishCalculator#1]
Hi. So, today i explored you project and have noticed that you did mistake at mockup of products list. At filename of product list you wrote "SundayDrinkPaty.pdf" instead of correct name : "SundayDrinkParty.pdf. I hoped i helped you 👍 💯

**Comment by messi3nik** [comment]
Salut! I just fix this issue! Thanks for help!
